# Generated by Django 4.2.4 on 2023-09-25 07:22

import bpbtest.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=bpbtest.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
    ]
